### ISSUE TITLE
2. Practicing more JSON parsing

### ISSUE THREAD

**Issue by cliffweitzman** [MakeSchool-Tutorials/JSON-API-Swift#4]
Please explain the bug you found here.
Tutorial should mention in 2nd challenge sections with movies that we pass in 
![image](https://cloud.githubusercontent.com/assets/3460171/16595924/5bb72a4c-42a6-11e6-8f55-dcb905621791.png)
so that feed entry 0 do not need to be included to find Price etc.

**Comment by dionlarson** [comment]
Fixed in https://github.com/MakeSchool-Tutorials/JSON-API-Swift-Starter/commit/646e5895edcdd9ff56180bc440b2d668eaf27c04
